### PR TITLE
Added countries, us states, mountains

### PR DESCRIPTION
**Pull request by Govind9**

### CODE REVIEW

**Comment by lintool** [comment]
typo - "countries"

**Comment by Govind9** [comment]
> typo - "countries"

The util script picks up the type from the csv file name so it was necessary to have "country" in the filename. To keep things consistent, the csv and py files were both named (intentionally) with this incorrect spelling.

**Comment by lintool** [comment]
Additional comments: `scripts/data/wikidata_countrys.csv` - lots of empty strings here?

Also, Taiwan (which is where I'm from) doesn't appear to be in the list.

**Comment by stephaniewhoo** [comment]
besides the additional comments above, I confirm this PR works

**Comment by Govind9** [comment]
> Additional comments: `scripts/data/wikidata_countrys.csv` - lots of empty strings here?

Any empty strings in the CSVs files are handled by loading script.

> Also, Taiwan (which is where I'm from) doesn't appear to be in the list.

Added subclasses like "state with limited recognition" (eg Taiwan) and "special administrative region of China" (eg Hong Kong) to the list of countries.

**Pull request merged**
